# Generated by Django 4.2 on 2024-07-10 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'manager'}, related_name='accountants', to=settings.AUTH_USER_MODEL),
        ),
    ]
