# Generated by Django 4.2 on 2024-07-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company name')),
                ('currency', models.CharField(blank=True, choices=[('INR', 'Rupee'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('AED', 'Dirham'), ('AED', 'Riyal')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='entries.category')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipts', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('payments', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('INR', 'Rupee'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('AED', 'Dirham'), ('AED', 'Riyal')], max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('entry_status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('manager_review_requested', 'Manager Review Requested'), ('manager_review_granted', 'Manager Review Granted')], default='pending', max_length=30)),
                ('entry_type', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('from_excel', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.company')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.subcategory')),
            ],
        ),
    ]
