# Generated by Django 4.2 on 2024-07-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_irregular',
            field=models.BooleanField(default=False),
        ),
    ]
